import {test} from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {admitRelease,verifyClosure,digest} from '../nixos/update-release.mjs';
import {runUpdate,finishTrial} from '../nixos/update-controller.mjs';
const {privateKey,publicKey}=generateKeyPairSync('ed25519');
const closure=Buffer.from('fixture closure');
const r={schema:'aiueos.release.v1',arch:'x86_64-linux',sequence:2,channel:'stable',issuedAt:1,expiresAt:10000,securityRisk:'high',applyRisk:'medium',closureSha256:digest(closure),closureBytes:closure.length,systemPath:'/nix/store/'+'a'.repeat(32)+'-nixos-system-qa',hostContract:'uuid-v1'};
const env=(v=r)=>{const b=Buffer.from(JSON.stringify(v));return {payload:b.toString('base64'),signatures:[{keyId:'qa',signature:sign(null,b,privateKey).toString('base64')}]};};
const trust={threshold:1,channel:'stable',keys:{qa:publicKey.export({type:'spki',format:'pem'})}};
const current={arch:r.arch,highestSequence:1,hostContract:'uuid-v1'};
test('exact signed release and closure; modified content refused',()=>{const a=admitRelease(env(),trust,current,2);assert.ok(verifyClosure(closure,a));assert.throws(()=>verifyClosure(Buffer.from('corrupt'),a));const e=env();e.payload=Buffer.from(JSON.stringify({...r,sequence:3})).toString('base64');assert.throws(()=>admitRelease(e,trust,current,2),/quorum/);});
test('quorum cannot count duplicate signer, wrong key or unsafe manifest',()=>{const e=env();e.signatures.push(e.signatures[0]);assert.throws(()=>admitRelease(e,{...trust,threshold:2},current,2));assert.throws(()=>admitRelease(e,{...trust,keys:{}},current,2));for(const patch of [{sequence:1},{arch:'aarch64-linux'},{expiresAt:2},{hostContract:'other'},{systemPath:'/tmp/script'},{securityRisk:'unknown'}])assert.throws(()=>admitRelease(env({...r,...patch}),trust,current,2));});
function fixture(action='stage') {let journal=null;const calls=[];const p={withLock:fn=>fn(),readJournal:async()=>journal,casJournal:async(old,next)=>{assert.equal(old,journal);journal=next;return next;},notify:async()=>calls.push('notify'),collectEvidence:async()=>({}),decide:async()=>({action,fleet:'none'}),fetchClosure:async()=>closure,importVerifiedClosure:async()=>calls.push('import'),restrictNewJobs:async()=>calls.push('restrict'),drain:async()=>calls.push('drain'),acquireFleetLease:async()=>({id:'qa'}),recheckActivation:async()=>true,prepareTrialBoot:async()=>calls.push('prepare'),reboot:async()=>calls.push('reboot'),releaseFleetLease:async()=>calls.push('release')};return {p,calls,journal:()=>journal,args:()=>({envelope:env(),trust,current,policy:{},now:2,providers:p})};}
test('stage is repeatable, notice persists, no reboot while downloading',async()=>{const f=fixture();await runUpdate(f.args());await runUpdate({...f.args(),now:3});assert.deepEqual(f.calls,['notify','import','import']);assert.equal(f.journal().pending.noticedAt,2);});
test('tampered release produces no notice, staging or restriction',async()=>{const f=fixture();const e=env();e.signatures=[];await assert.rejects(runUpdate({...f.args(),envelope:e}));assert.deepEqual(f.calls,[]);});
test('activation rechecks evidence under atomic fleet lease',async()=>{const f=fixture('trial-boot');f.p.recheckActivation=async()=>false;await runUpdate(f.args());assert.deepEqual(f.calls,['notify','release']);});
test('trial commits only after local health, failure blocks same release',async()=>{const f=fixture('trial-boot');await runUpdate(f.args());assert.deepEqual(f.calls,['notify','prepare','reboot']);f.p.collectLocalHealth=async()=>({localHealth:'fail'});f.p.decideTrial=async()=>({action:'rollback'});f.p.restorePreviousBoot=async()=>f.calls.push('rollback');await finishTrial({journal:f.journal(),providers:f.p});assert.ok(f.journal().blocked.length===1);const v=await runUpdate(f.args());assert.equal(v.reason,'previous-trial-failed');});

test('durable high-water allows only exact pending release to resume',()=>{const e=env();const a=admitRelease(e,trust,current,2);assert.doesNotThrow(()=>admitRelease(e,trust,{...current,highestSequence:2,pendingManifestHash:a.manifestHash},2));assert.throws(()=>admitRelease(env({...r,applyRisk:'low'}),trust,{...current,highestSequence:2,pendingManifestHash:a.manifestHash},2));});
test('two independent Ed25519 keys satisfy a two-signer policy',()=>{const k=generateKeyPairSync('ed25519'),e=env(),bytes=Buffer.from(e.payload,'base64');e.signatures.push({keyId:'independent',signature:sign(null,bytes,k.privateKey).toString('base64')});assert.equal(admitRelease(e,{...trust,threshold:2,keys:{...trust.keys,independent:k.publicKey.export({type:'spki',format:'pem'})}},current,2).signers.length,2);});
