import test from 'node:test';
import assert from 'node:assert/strict';
import {VoiceControl,secretCharacters} from '../nixos/voice-control.mjs';
import {VoiceActivity,wav} from '../nixos/voice-agent.mjs';
const menu={revision:1,language:'ja',kind:'menu',message:'接続方法',choices:[{id:'wifi',label:'Wi-Fi'},{id:'offline',label:'ネットなし'}],canBack:true};
function harness(model=async()=>({action:'choose',choice:'wifi',speech:''})){const actions=[],spoken=[];const control=new VoiceControl({model,dispatch:a=>actions.push(a),speak:async text=>spoken.push(text)});return {control,actions,spoken};}
test('AI selects only current UI candidates, duplicate utterances execute once',async()=>{const h=harness();h.control.update(menu);await h.control.utterance('Wi-Fiにつなぎたい',{id:'one'});await h.control.utterance('Wi-Fiにつなぎたい',{id:'one'});assert.equal(h.actions.length,1);assert.equal(h.actions[0].value,'wifi');});
test('arbitrary tool, command, path and model erase requests are refused',async()=>{for(const reply of [{action:'exec',speech:'',choice:'sh'},{action:'erase',speech:'',choice:'/dev/nvme0n1'},{action:'choose',speech:'',choice:'/dev/sda'},{action:'continue',speech:''}]){const h=harness(async()=>reply);h.control.update(menu);assert.equal((await h.control.utterance('説明して')).status,'refused');assert.equal(h.actions.length,0);}});
test('state changes and invalidation cancel in-flight model results',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));h.control.update(menu);const response=h.control.utterance('Wi-Fi');h.control.update({...menu,revision:2,choices:[{id:'other',label:'Other'}]});resolve({action:'choose',choice:'wifi',speech:''});assert.equal((await response).status,'stale');assert.equal(h.actions.length,0);assert.equal(h.control.update(menu),false);});
test('secret spelling never calls model or speaks secret; completion passes to backend only',async()=>{const h=harness(async()=>{throw Error('Secret leaked to model');});h.control.update({revision:1,language:'ja',kind:'secret',canBack:true});for(const words of ['大文字エー','ビー','アンダースコア','7'])await h.control.utterance(words);await h.control.utterance('一文字消して');await h.control.utterance('8');await h.control.utterance('入力完了');assert.equal(h.actions[0].value,'Ab_8');assert.equal(h.control.secret,'');assert.ok(h.spoken.every(s=>!s.includes('Ab_8')));assert.equal(secretCharacters('uppercase a'),'A');});
test('secret cancel clears memory; unknown character is refused',async()=>{const h=harness();h.control.update({revision:1,language:'en',kind:'secret',canBack:true});await h.control.utterance('hello');await h.control.utterance('back');assert.equal(h.control.secret,'');assert.equal(h.actions[0].action,'back');assert.equal(secretCharacters('execute shell'),null);});
test('destructive consent is fresh, exact, serial-bound and unavailable to model',async()=>{let now=0;const h=harness(async()=>{throw Error('Erase reached model');});h.control.now=()=>now;h.control.update({revision:1,language:'ja',kind:'erase',target:'/dev/nvme0n1',serial:'QA1234',canBack:true});assert.equal((await h.control.utterance('はい')).status,'confirmation');assert.equal(h.actions.length,0);now=46000;assert.equal((await h.control.utterance('番号1234のディスクを消してインストール')).status,'confirmation');assert.equal(h.actions.length,0);await h.control.utterance('番号1234のディスクを消してインストール');assert.equal(h.actions.length,1);assert.equal(h.actions[0].action,'erase');assert.equal(h.actions[0].value,'/dev/nvme0n1');});
test('missing serial blocks voice erase, changed target invalidates old confirmation',async()=>{const h=harness();h.control.update({revision:1,kind:'erase',language:'en',target:'/dev/vda',serial:null});assert.equal((await h.control.utterance('erase')).status,'refused');h.control.update({revision:2,kind:'erase',language:'en',target:'/dev/vdb',serial:'5678'});await h.control.utterance('install');h.control.update({revision:3,kind:'erase',language:'en',target:'/dev/vdb',serial:'9999'});await h.control.utterance('erase 5678 and install');assert.equal(h.actions.length,0);});
test('approval sound transport cannot approve an account',async()=>{const h=harness(async()=>({action:'approve',speech:'',choice:'owner'}));h.control.update({revision:1,language:'en',kind:'approval',canBack:true});assert.equal((await h.control.utterance('approve me')).status,'refused');await h.control.utterance('send code');assert.equal(h.actions[0].action,'send_code');});
test('segmented PCM voice activity uses silence boundary and skips silence',()=>{let count=0,pcm;const vad=new VoiceActivity({onSpeech:p=>{count++;pcm=p;}});vad.push(Buffer.alloc(640*30));assert.equal(count,0);const tone=Buffer.alloc(640*20);for(let i=0;i<tone.length;i+=2)tone.writeInt16LE(2000,i);for(let i=0;i<tone.length;i+=37)vad.push(tone.subarray(i,i+37));vad.push(Buffer.alloc(640*25));assert.equal(count,1);assert.equal(wav(pcm).readUInt32LE(24),16000);});
test('voice audio controls are fixed operations and never intercept secret spelling',async()=>{const h=harness();h.control.update(menu);await h.control.utterance('音量を上げて');assert.equal(h.actions[0].action,'control');assert.equal(h.actions[0].value,'volume_up');h.control.update({revision:2,language:'ja',kind:'secret'});await h.control.utterance('音楽を止めて');assert.equal(h.actions.length,1);});
test('audio control cancels prior disk confirmation instead of carrying consent forward',async()=>{const h=harness();h.control.update({revision:1,language:'ja',kind:'erase',target:'/dev/vda',serial:'QA1234'});await h.control.utterance('インストールして');await h.control.utterance('音量を下げて');await h.control.utterance('番号1234のディスクを消してインストール');assert.equal(h.actions.filter(x=>x.action==='erase').length,0);});
test('explicit lower case survives ASR returning an uppercase Latin character',()=>{assert.equal(secretCharacters('小文字B'),'b');assert.equal(secretCharacters('lowercase Q'),'q');});

test('explicit spoken secret phrases parse without exposing or silently completing empty secrets',async()=>{assert.equal(secretCharacters('小文字のBを入力'),'b');assert.equal(secretCharacters('大文字のエーを入力。'),'A');assert.equal(secretCharacters('数字の7を入力'),'7');assert.equal(secretCharacters('数字の七を入力'),'7');assert.equal(secretCharacters('数字のfooを入力'),null);const h=harness();h.control.update({revision:1,language:'ja',kind:'secret'});await h.control.utterance('入力完了');assert.equal(h.actions.length,0);});

test('English punctuation and named symbols do not become accidental password characters',()=>{assert.equal(secretCharacters('lowercase B.'),'b');assert.equal(secretCharacters('digit seven.'),'7');assert.equal(secretCharacters('uppercase bravo.'),'B');assert.equal(secretCharacters('dot.'),'.');assert.equal(secretCharacters('underscore'),'_');});
