// Audible FSK transports a public, expiring approval code; never credentials.
export const sampleRate=16000, symbolSamples=320;
const sync=[0x55,0x55,0x55,0xd3,0x91];
export function crc16(bytes){let c=0xffff;for(const b of bytes){c^=b<<8;for(let j=0;j<8;j++)c=((c<<1)^((c&0x8000)?0x1021:0))&0xffff;}return c;}
export function packet(code){if(!/^[A-Z0-9_-]{10}$/.test(code))throw Error('Invalid approval code');const body=[1,...new TextEncoder().encode(code)],crc=crc16(body);return Uint8Array.from([...sync,...body,crc>>8,crc&255]);}
export function encode(code){const bytes=packet(code),out=new Float32Array((bytes.length*8+8)*symbolSamples);let pos=4*symbolSamples;for(const byte of bytes)for(let b=7;b>=0;b--){const hz=(byte>>b)&1?2200:1200;for(let n=0;n<symbolSamples;n++){const fade=Math.min(1,n/16,(symbolSamples-1-n)/16);out[pos++]=0.12*fade*Math.sin(2*Math.PI*hz*n/sampleRate);}}return out;}
function energy(samples,start,hz){let re=0,im=0;for(let n=0;n<symbolSamples;n++){const a=2*Math.PI*hz*n/sampleRate,v=samples[start+n];re+=v*Math.cos(a);im+=v*Math.sin(a);}return re*re+im*im;}
export function decode(samples){const count=18*8,needed=count*symbolSamples;for(let start=0;start+needed<=samples.length;start+=40){const bytes=[];let good=true;for(let i=0;i<count;i++){const a=energy(samples,start+i*symbolSamples,1200),b=energy(samples,start+i*symbolSamples,2200);if(Math.max(a,b)<0.1){good=false;break;}const bit=b>a?1:0,index=i>>3;bytes[index]=((bytes[index]||0)<<1)|bit;if(i<40&&bit!==((sync[index]>>(7-(i&7)))&1)){good=false;break;}}if(!good)continue;const body=bytes.slice(5,16);if(body[0]!==1||crc16(body)!==((bytes[16]<<8)|bytes[17]))continue;const code=new TextDecoder().decode(Uint8Array.from(body.slice(1)));if(/^[A-Z0-9_-]{10}$/.test(code))return code;}return null;}
export const approvalUri=code=>{packet(code);return 'https://setup.murakumo.cloud/#device-link?code='+code;};
